spring:
  application:
    name: longxia-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://146.56.192.104:3306/longxia
    username: longxia_zhouwei
    password: 8bejz7QR3EyeM2f6

server:
  port: 8923
  servlet:
    context-path: /api
spring.servlet.multipart:
  max-file-size: 5MB
  max-request-size: 10MB

file:
  upload-dir: uploads



# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.example.longxia.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
